server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false 
    fetchRegistry: false
    -- set registerWithEureka & fetchRegistry to false 
    -- indicate this is a eureka server, not a client
    -- dont need to register to itself
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/